//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentUsos.Resources.LocalizedStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentUsos.Resources.LocalizedStrings.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studencki USOS is an unofficial application developed by a student at Poznań University of Technology majoring in Computer Science as part of the .NET Scientific Circle of Poznań University of Technology..
        /// </summary>
        internal static string AboutAppPage_AboutApp {
            get {
                return ResourceManager.GetString("AboutAppPage_AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person responsible for applications - Olivier Betman, Poznań University of Technology..
        /// </summary>
        internal static string AboutAppPage_Developer {
            get {
                return ResourceManager.GetString("AboutAppPage_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact for matters related to the application (questions, suggestions, errors, etc.):.
        /// </summary>
        internal static string AboutAppPage_DeveloperContact {
            get {
                return ResourceManager.GetString("AboutAppPage_DeveloperContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string AboutAppPage_DeveloperTitle {
            get {
                return ResourceManager.GetString("AboutAppPage_DeveloperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string AboutAppPage_PersonalData {
            get {
                return ResourceManager.GetString("AboutAppPage_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application does not send data outside the user&apos;s device. The only form of data collection is logs, which are used for diagnostic purposes, but they are not automatically sent. Logs can only be sent by the user from the application settings (previous page)..
        /// </summary>
        internal static string AboutAppPage_PersonalDataText1 {
            get {
                return ResourceManager.GetString("AboutAppPage_PersonalDataText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs are automatically deleted from the device after 2 days..
        /// </summary>
        internal static string AboutAppPage_PersonalDataText2 {
            get {
                return ResourceManager.GetString("AboutAppPage_PersonalDataText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download activities.
        /// </summary>
        internal static string ActivitiesPage_DownloadActivities {
            get {
                return ResourceManager.GetString("ActivitiesPage_DownloadActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string ActivitiesPage_Downloading {
            get {
                return ResourceManager.GetString("ActivitiesPage_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even week.
        /// </summary>
        internal static string ActivitiesPage_EvenWeek {
            get {
                return ResourceManager.GetString("ActivitiesPage_EvenWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd week.
        /// </summary>
        internal static string ActivitiesPage_OddWeek {
            get {
                return ResourceManager.GetString("ActivitiesPage_OddWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string ActivitiesPage_Room {
            get {
                return ResourceManager.GetString("ActivitiesPage_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ActivitiesPage_Today {
            get {
                return ResourceManager.GetString("ActivitiesPage_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string ActivitiesScheduleUpdateNotification_Added {
            get {
                return ResourceManager.GetString("ActivitiesScheduleUpdateNotification_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string ActivitiesScheduleUpdateNotification_Removed {
            get {
                return ResourceManager.GetString("ActivitiesScheduleUpdateNotification_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string ActivitiesScheduleUpdateNotification_Updated {
            get {
                return ResourceManager.GetString("ActivitiesScheduleUpdateNotification_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse.
        /// </summary>
        internal static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student USOS.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string AppName_FirstPart {
            get {
                return ResourceManager.GetString("AppName_FirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USOS.
        /// </summary>
        internal static string AppName_SecondPart {
            get {
                return ResourceManager.GetString("AppName_SecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        internal static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break.
        /// </summary>
        internal static string CalendarEventType_Break {
            get {
                return ResourceManager.GetString("CalendarEventType_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dean&apos;s.
        /// </summary>
        internal static string CalendarEventType_Dean {
            get {
                return ResourceManager.GetString("CalendarEventType_Dean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exam session.
        /// </summary>
        internal static string CalendarEventType_ExamSession {
            get {
                return ResourceManager.GetString("CalendarEventType_ExamSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to holiday.
        /// </summary>
        internal static string CalendarEventType_Holidays {
            get {
                return ResourceManager.GetString("CalendarEventType_Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to holiday.
        /// </summary>
        internal static string CalendarEventType_PublicHolidays {
            get {
                return ResourceManager.GetString("CalendarEventType_PublicHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rector&apos;s.
        /// </summary>
        internal static string CalendarEventType_Rector {
            get {
                return ResourceManager.GetString("CalendarEventType_Rector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar notifications.
        /// </summary>
        internal static string CalendarNotifications {
            get {
                return ResourceManager.GetString("CalendarNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M|T|W|T|F|S|S.
        /// </summary>
        internal static string CalendarPage_DaysOfWeekLabels {
            get {
                return ResourceManager.GetString("CalendarPage_DaysOfWeekLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Calendar.
        /// </summary>
        internal static string CalendarPage_GoogleCalendar {
            get {
                return ResourceManager.GetString("CalendarPage_GoogleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added calendars.
        /// </summary>
        internal static string CalendarSettingsPage_AddedCalendars {
            get {
                return ResourceManager.GetString("CalendarSettingsPage_AddedCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some calendars allow you to export calendar in form of URL to iCalendar file (.ics). Using the button beside and the link you can connect e.g. Google Calendar to this app.
        /// </summary>
        internal static string CalendarSettingsPage_HelpDescription {
            get {
                return ResourceManager.GetString("CalendarSettingsPage_HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string CalendarSettingsPage_HelpTItle {
            get {
                return ResourceManager.GetString("CalendarSettingsPage_HelpTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert URL to iCalendar file (.ics) of calendar which you want to import.
        /// </summary>
        internal static string CalendarSettingsPage_NewCalendarDescription {
            get {
                return ResourceManager.GetString("CalendarSettingsPage_NewCalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New calendar.
        /// </summary>
        internal static string CalendarSettingsPage_NewCalendarTitle {
            get {
                return ResourceManager.GetString("CalendarSettingsPage_NewCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        internal static string Campus {
            get {
                return ResourceManager.GetString("Campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus map.
        /// </summary>
        internal static string CampusMap {
            get {
                return ResourceManager.GetString("CampusMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string CampusMap_Map {
            get {
                return ResourceManager.GetString("CampusMap_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion not sent: Name for given room can be suggested only once.
        /// </summary>
        internal static string CampusMapPage_SuggestionAlreadyRecorder {
            get {
                return ResourceManager.GetString("CampusMapPage_SuggestionAlreadyRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion sent successfully.
        /// </summary>
        internal static string CampusMapPage_SuggestionSentSuccessfully {
            get {
                return ResourceManager.GetString("CampusMapPage_SuggestionSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion could not be saved.
        /// </summary>
        internal static string CampusMapPage_SuggestionUnexpectedStatusCode {
            get {
                return ResourceManager.GetString("CampusMapPage_SuggestionUnexpectedStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change in activities schedule.
        /// </summary>
        internal static string ChangeInActivitiesSchedule {
            get {
                return ResourceManager.GetString("ChangeInActivitiesSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksums.
        /// </summary>
        internal static string Checksums {
            get {
                return ResourceManager.GetString("Checksums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string Dashboard_Hello {
            get {
                return ResourceManager.GetString("Dashboard_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming events.
        /// </summary>
        internal static string Dashboard_NextEvents {
            get {
                return ResourceManager.GetString("Dashboard_NextEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day off!.
        /// </summary>
        internal static string DayOff {
            get {
                return ResourceManager.GetString("DayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Tunnel allows connecting to other servers using the identifier of Dev Tunnel. Do not input here any values unless given by application&apos;s developer. One of the main purposes of Dev Tunnels is connecting to development server. If you connected to one and your app stops working remove the Dev Tunnel using button below..
        /// </summary>
        internal static string DevTunnelPage_Description {
            get {
                return ResourceManager.GetString("DevTunnelPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep between app runs.
        /// </summary>
        internal static string DevTunnelPage_KeepBetweenAppRuns {
            get {
                return ResourceManager.GetString("DevTunnelPage_KeepBetweenAppRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tunnel.
        /// </summary>
        internal static string DevTunnelPage_RemoveTunnel {
            get {
                return ResourceManager.GetString("DevTunnelPage_RemoveTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities schedule background synchronization.
        /// </summary>
        internal static string DiagnosisSubpage_ActivitiesBackgroundSynchronization {
            get {
                return ResourceManager.GetString("DiagnosisSubpage_ActivitiesBackgroundSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string Errors_ConnectionError {
            get {
                return ResourceManager.GetString("Errors_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Errors_Error {
            get {
                return ResourceManager.GetString("Errors_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Errors_LoadingError {
            get {
                return ResourceManager.GetString("Errors_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to USOS API error.
        /// </summary>
        internal static string Errors_USOSAPIConnectionError {
            get {
                return ResourceManager.GetString("Errors_USOSAPIConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final grades.
        /// </summary>
        internal static string FinalGrades {
            get {
                return ResourceManager.GetString("FinalGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        internal static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts into average.
        /// </summary>
        internal static string GradesPage_CountIntoAverage {
            get {
                return ResourceManager.GetString("GradesPage_CountIntoAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit grades.
        /// </summary>
        internal static string GradesPage_EditGrades {
            get {
                return ResourceManager.GetString("GradesPage_EditGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No final grades to show.
        /// </summary>
        internal static string GradesPage_Empty {
            get {
                return ResourceManager.GetString("GradesPage_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I term.
        /// </summary>
        internal static string GradesPage_FirstTerm {
            get {
                return ResourceManager.GetString("GradesPage_FirstTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholarship calculator.
        /// </summary>
        internal static string GradesPage_ScholarshipCalculator {
            get {
                return ResourceManager.GetString("GradesPage_ScholarshipCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II term.
        /// </summary>
        internal static string GradesPage_SecondTerm {
            get {
                return ResourceManager.GetString("GradesPage_SecondTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string LackOf {
            get {
                return ResourceManager.GetString("LackOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturers.
        /// </summary>
        internal static string Lecturers {
            get {
                return ResourceManager.GetString("Lecturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out.
        /// </summary>
        internal static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string LoggingOut_Confirmation {
            get {
                return ResourceManager.GetString("LoggingOut_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string LoggingPermissionDescription_Activities {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string LoggingPermissionDescription_Calendar {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final grades.
        /// </summary>
        internal static string LoggingPermissionDescription_FinalGrades {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_FinalGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string LoggingPermissionDescription_Groups {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string LoggingPermissionDescription_Payments {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string LoggingPermissionDescription_Progs {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_Progs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        internal static string LoggingPermissionDescription_Surveys {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User (first name, last name, index numer).
        /// </summary>
        internal static string LoggingPermissionDescription_User {
            get {
                return ResourceManager.GetString("LoggingPermissionDescription_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I allow collecting information from following modules for diagnostic purposes (logs).
        /// </summary>
        internal static string LoggingPermissionPopup_Title {
            get {
                return ResourceManager.GetString("LoggingPermissionPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing permissions:.
        /// </summary>
        internal static string Login_MissingScopes {
            get {
                return ResourceManager.GetString("Login_MissingScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input PIN code:.
        /// </summary>
        internal static string LoginPage_InputPIN {
            get {
                return ResourceManager.GetString("LoginPage_InputPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue with signing in?.
        /// </summary>
        internal static string LoginPage_IssueWithLogin {
            get {
                return ResourceManager.GetString("LoginPage_IssueWithLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in failed.
        /// </summary>
        internal static string LoginPage_LoginFailed {
            get {
                return ResourceManager.GetString("LoginPage_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using PIN code.
        /// </summary>
        internal static string LoginPage_LoginWithPIN {
            get {
                return ResourceManager.GetString("LoginPage_LoginWithPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in as guest.
        /// </summary>
        internal static string LoginPage_SigInAsGuest {
            get {
                return ResourceManager.GetString("LoginPage_SigInAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string LoginPage_TryAgain {
            get {
                return ResourceManager.GetString("LoginPage_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again using PIN code.
        /// </summary>
        internal static string LoginPage_TryAgainWithPinCode {
            get {
                return ResourceManager.GetString("LoginPage_TryAgainWithPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all logs.
        /// </summary>
        internal static string LogsPage_RemoveAll {
            get {
                return ResourceManager.GetString("LogsPage_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all logs.
        /// </summary>
        internal static string LogsPage_SendAllLogs {
            get {
                return ResourceManager.GetString("LogsPage_SendAllLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        internal static string Modification {
            get {
                return ResourceManager.GetString("Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s USOS: Poznań University of Technology.
        /// </summary>
        internal static string MorePage_AppName {
            get {
                return ResourceManager.GetString("MorePage_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days in advance.
        /// </summary>
        internal static string MorePage_DaysBefore {
            get {
                return ResourceManager.GetString("MorePage_DaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string MorePage_NotifyAt {
            get {
                return ResourceManager.GetString("MorePage_NotifyAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke access to USOS.
        /// </summary>
        internal static string MorePage_RevokeAccess {
            get {
                return ResourceManager.GetString("MorePage_RevokeAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options.
        /// </summary>
        internal static string MultipleChoicePopup_Empty {
            get {
                return ResourceManager.GetString("MultipleChoicePopup_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t find the appropriate settings page.
        /// </summary>
        internal static string NotificationsDiagnosis_AutoStartCouldNotOpenSettings {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_AutoStartCouldNotOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if device manufacturer defined additional permission which might block this application from receiving notifications after device reboot.
        /// </summary>
        internal static string NotificationsDiagnosis_AutoStartTitle {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_AutoStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer of your device might have defined a permission which could block this application from starting after rebooting the device. By clicking button below the app will try to forward you to the right settings page..
        /// </summary>
        internal static string NotificationsDiagnosis_AutoStartWarningMessage {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_AutoStartWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow running in background.
        /// </summary>
        internal static string NotificationsDiagnosis_BackgroundRestrictedButton {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_BackgroundRestrictedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is not allowed to run in background, this could potentially block some notifications..
        /// </summary>
        internal static string NotificationsDiagnosis_BackgroundRestrictedErrorDescription {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_BackgroundRestrictedErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if application is restricted from running in the background.
        /// </summary>
        internal static string NotificationsDiagnosis_BackgroundRestrictedTitle {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_BackgroundRestrictedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device has battery optimization enabled for this app, this might break notifications.
        /// </summary>
        internal static string NotificationsDiagnosis_BatteryOptimizationErrorDescription {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_BatteryOptimizationErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if battery optimization is enabled for this application.
        /// </summary>
        internal static string NotificationsDiagnosis_BatteryOptimizationTitle {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_BatteryOptimizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing has failed. Next steps:
        ///1. Server could be down - try again later.
        ///2. Something might be wrong on the server - try signing out and signing in again.
        ///3. If issue persists try contacting support (ways of contact can be found in Settings -&gt; App information)..
        /// </summary>
        internal static string NotificationsDiagnosis_FcmTokenErrorMessage {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_FcmTokenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating device information on the server.
        /// </summary>
        internal static string NotificationsDiagnosis_FcmTokenTitle {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_FcmTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to settings.
        /// </summary>
        internal static string NotificationsDiagnosis_GoToSettings {
            get {
                return ResourceManager.GetString("NotificationsDiagnosis_GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications about changes to the activities schedule.
        /// </summary>
        internal static string NotificationsSubpage_NotificationsAboutChangesInSchedule {
            get {
                return ResourceManager.GetString("NotificationsSubpage_NotificationsAboutChangesInSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        internal static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled due to spam.
        /// </summary>
        internal static string OperationCanceledDueToSpam {
            get {
                return ResourceManager.GetString("OperationCanceledDueToSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        internal static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        internal static string PaymentsPage_AccountNumber {
            get {
                return ResourceManager.GetString("PaymentsPage_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied account number.
        /// </summary>
        internal static string PaymentsPage_AccountNumberCopied {
            get {
                return ResourceManager.GetString("PaymentsPage_AccountNumberCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string PaymentsPage_Amount {
            get {
                return ResourceManager.GetString("PaymentsPage_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payments to display.
        /// </summary>
        internal static string PaymentsPage_NoPayments {
            get {
                return ResourceManager.GetString("PaymentsPage_NoPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string PaymentsPage_PaymentDeadline {
            get {
                return ResourceManager.GetString("PaymentsPage_PaymentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing permissions, some functions might not work. Log in again..
        /// </summary>
        internal static string Permissions_MissingPermissionsDescription {
            get {
                return ResourceManager.GetString("Permissions_MissingPermissionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email copied.
        /// </summary>
        internal static string PersonDetailsPage_EmailCopied {
            get {
                return ResourceManager.GetString("PersonDetailsPage_EmailCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number copied.
        /// </summary>
        internal static string PersonDetailsPage_PhoneNumberCopied {
            get {
                return ResourceManager.GetString("PersonDetailsPage_PhoneNumberCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications.
        /// </summary>
        internal static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new grade!.
        /// </summary>
        internal static string PushNotifications_UsosNewGrade_DefaultTitleAndBody {
            get {
                return ResourceManager.GetString("PushNotifications_UsosNewGrade_DefaultTitleAndBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string PushNotifications_UsosNewGrade_InterpretedBodySeparator {
            get {
                return ResourceManager.GetString("PushNotifications_UsosNewGrade_InterpretedBodySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New grade.
        /// </summary>
        internal static string PushNotifications_UsosNewGrade_InterpretedTitle {
            get {
                return ResourceManager.GetString("PushNotifications_UsosNewGrade_InterpretedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use only letters, numbers, spaces, and basic punctuation (.,-_).
        /// </summary>
        internal static string RoomDetailsPage_AllowedCharacters {
            get {
                return ResourceManager.GetString("RoomDetailsPage_AllowedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative names.
        /// </summary>
        internal static string RoomDetailsPage_AlternativeNames {
            get {
                return ResourceManager.GetString("RoomDetailsPage_AlternativeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        internal static string RoomDetailsPage_RoomName {
            get {
                return ResourceManager.GetString("RoomDetailsPage_RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string RoomDetailsPage_Send {
            get {
                return ResourceManager.GetString("RoomDetailsPage_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest room name.
        /// </summary>
        internal static string RoomDetailsPage_SuggestRoomName {
            get {
                return ResourceManager.GetString("RoomDetailsPage_SuggestRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No surveys to fill.
        /// </summary>
        internal static string SatisfactionSurveysPage_Empty {
            get {
                return ResourceManager.GetString("SatisfactionSurveysPage_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semesters.
        /// </summary>
        internal static string Semesters {
            get {
                return ResourceManager.GetString("Semesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out by USOS. This usually happens when the application is deprived of permissions to your data by the user or the USOS password is changed. Sign in again to use the app..
        /// </summary>
        internal static string SessionInvalidMessage_Description {
            get {
                return ResourceManager.GetString("SessionInvalidMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired.
        /// </summary>
        internal static string SessionInvalidMessage_Title {
            get {
                return ResourceManager.GetString("SessionInvalidMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about application.
        /// </summary>
        internal static string SettingsPage_AppInfo {
            get {
                return ResourceManager.GetString("SettingsPage_AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured changes.
        /// </summary>
        internal static string SettingsPage_ApplicationSubPage_WhatsNewFeatured {
            get {
                return ResourceManager.GetString("SettingsPage_ApplicationSubPage_WhatsNewFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General changes.
        /// </summary>
        internal static string SettingsPage_ApplicationSubPage_WhatsNewGeneralChanges {
            get {
                return ResourceManager.GetString("SettingsPage_ApplicationSubPage_WhatsNewGeneralChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background synchronization.
        /// </summary>
        internal static string SettingsPage_BackgroundSynchronization {
            get {
                return ResourceManager.GetString("SettingsPage_BackgroundSynchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events from calendar.
        /// </summary>
        internal static string SettingsPage_CalendarEvents {
            get {
                return ResourceManager.GetString("SettingsPage_CalendarEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be fully visible after restarting the app..
        /// </summary>
        internal static string SettingsPage_ChangingLanguageMessage {
            get {
                return ResourceManager.GetString("SettingsPage_ChangingLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string SettingsPage_Logs {
            get {
                return ResourceManager.GetString("SettingsPage_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged information.
        /// </summary>
        internal static string SettingsPage_LogsAllowedModulesButton {
            get {
                return ResourceManager.GetString("SettingsPage_LogsAllowedModulesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset local data.
        /// </summary>
        internal static string SettingsPage_ResetLocalData {
            get {
                return ResourceManager.GetString("SettingsPage_ResetLocalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will still run on locally stored data, if you want to delete this data log out of the application..
        /// </summary>
        internal static string SettingsPage_RevokeAccessDescription {
            get {
                return ResourceManager.GetString("SettingsPage_RevokeAccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke access.
        /// </summary>
        internal static string SettingsPage_RevokeAccessTitle {
            get {
                return ResourceManager.GetString("SettingsPage_RevokeAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing/diagnostic.
        /// </summary>
        internal static string SettingsPage_TestingTabTitle {
            get {
                return ResourceManager.GetString("SettingsPage_TestingTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        internal static string Surveys {
            get {
                return ResourceManager.GetString("Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys to fill.
        /// </summary>
        internal static string SurveysPage_SurveysToFill {
            get {
                return ResourceManager.GetString("SurveysPage_SurveysToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting.
        /// </summary>
        internal static string Troubleshooting {
            get {
                return ResourceManager.GetString("Troubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznań University Of Technology.
        /// </summary>
        internal static string UniversityName {
            get {
                return ResourceManager.GetString("UniversityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new.
        /// </summary>
        internal static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget with activities schedule.
        /// </summary>
        internal static string WhatsNewItem_ActivitiesScheduleWidget {
            get {
                return ResourceManager.GetString("WhatsNewItem_ActivitiesScheduleWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on your settings receiving notifications might be blocked. You can perform an automatic check in Settings -&gt; Notifications -&gt; Troubleshooting..
        /// </summary>
        internal static string WhatsNewItem_NewGradeDetails {
            get {
                return ResourceManager.GetString("WhatsNewItem_NewGradeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications for new grade..
        /// </summary>
        internal static string WhatsNewItem_NewGradeTitle {
            get {
                return ResourceManager.GetString("WhatsNewItem_NewGradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * For this feature to work properly, the device should not prevent the app from running in the background. To verify your settings, you can use the option available under Settings → Notifications → Troubleshooting..
        /// </summary>
        internal static string WhatsNewItem_ScheduleChangeNotificationDescription1 {
            get {
                return ResourceManager.GetString("WhatsNewItem_ScheduleChangeNotificationDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** The check covers the next 7 days, including today..
        /// </summary>
        internal static string WhatsNewItem_ScheduleChangeNotificationDescription2 {
            get {
                return ResourceManager.GetString("WhatsNewItem_ScheduleChangeNotificationDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications about changes in schedule.
        /// </summary>
        internal static string WhatsNewItem_ScheduleChangeNotificationTitle {
            get {
                return ResourceManager.GetString("WhatsNewItem_ScheduleChangeNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string WhatsNewPage_Next {
            get {
                return ResourceManager.GetString("WhatsNewPage_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string WhatsNewPage_Skip {
            get {
                return ResourceManager.GetString("WhatsNewPage_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
